#! /bin/bash

#
# Updates the childsplay website (straight from git)
# Located at /nfs/ca/info/research_www/childsplay on flip
# under the 'childsplay' group
#

cd /nfs/ca/info/research_www/childsplay
git stash
git checkout main
git pull

# reset permissions back for the 'childsplay' group
# (git overrides them)
chmod -R g+rwX *

# rebuild the site with drafts enabled
hugo -D
